apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-test1
  labels:
    app: java-test1
spec:
  replicas: 15
  selector:
    matchLabels:
      app: java-test1
  template:
    metadata:
      labels:
        app: java-test1
    spec:
      containers:
      - name: java-test1
        image: 192.168.3.228:30844/java-test1:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: java-test1
spec:
  selector:
    app: java-test1
  ports:
    - protocol: TCP
      port: 8123
  type: NodePort
